version: '3.8'

services:
  app:
    build: .
    ports:
      - 8443:8443
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: grupo15SQL
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:9.2
    environment:
      MYSQL_ROOT_PASSWORD: grupo15SQL
      MYSQL_DATABASE: bookshop
    volumes:
      - ./mysql:/var/lib/mysql
